import type { Metadata } from "next";
import { Geist, Geist_Mono, Judson } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const judson = Judson({
  subsets: ["latin"],
  variable: "--font-judson",
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${judson.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
